In [3]:
import tensorflow as tf

2023-03-27 10:15:07.144532: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-03-27 10:15:08.350975: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda-12.0/lib64:/usr/local/cuda-12.0/lib64::/usr/local/tensorrt/lib/:/usr/local/tensorrt/lib/
2023-03-27 10:15:08.351168: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda-12.0/lib6

In [4]:
x = tf.constant([[1.5,2.4,3.4],
              [.4,.5,6.5]])

2023-03-27 10:15:09.841524: E tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:267] failed call to cuInit: CUDA_ERROR_UNKNOWN: unknown error
2023-03-27 10:15:09.841572: I tensorflow/compiler/xla/stream_executor/cuda/cuda_diagnostics.cc:169] retrieving CUDA diagnostic information for host: kalyan-linux
2023-03-27 10:15:09.841584: I tensorflow/compiler/xla/stream_executor/cuda/cuda_diagnostics.cc:176] hostname: kalyan-linux
2023-03-27 10:15:09.841703: I tensorflow/compiler/xla/stream_executor/cuda/cuda_diagnostics.cc:200] libcuda reported version is: 525.89.2
2023-03-27 10:15:09.841745: I tensorflow/compiler/xla/stream_executor/cuda/cuda_diagnostics.cc:204] kernel reported version is: 525.89.2
2023-03-27 10:15:09.841759: I tensorflow/compiler/xla/stream_executor/cuda/cuda_diagnostics.cc:310] kernel version seems to match DSO: 525.89.2
2023-03-27 10:15:09.842954: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Net

In [5]:
tf.nn.softmax(x,axis=1)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0.09856588, 0.24243297, 0.6590011 ],
       [0.00223233, 0.0024671 , 0.99530053]], dtype=float32)>

In [6]:
x@tf.transpose(x)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[19.57, 23.9 ],
       [23.9 , 42.66]], dtype=float32)>

In [7]:
tf.reduce_sum(x)

<tf.Tensor: shape=(), dtype=float32, numpy=14.700001>

In [9]:
tf.convert_to_tensor([1,2,3])


<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [10]:
tf.reduce_sum([1,2,3])


<tf.Tensor: shape=(), dtype=int32, numpy=6>

In [16]:
if tf.config.list_physical_devices('GPU'):
  print("TensorFlow **IS** using the GPU")
else:
  print("TensorFlow **IS NOT** using the GPU")


TensorFlow **IS NOT** using the GPU


In [13]:
tf.config.list_physical_devices

<function tensorflow.python.framework.config.list_physical_devices(device_type=None)>

In [17]:
print("Num GPUs Available: ", len(tf.config.list_physical_devices('GPU')))


Num GPUs Available:  0
